### ISSUE TITLE
Storing graph nodes

### ISSUE THREAD

**Issue by mrjjwright** [zandaqo/structurae#10]
I am building a pretty big graph built up of sub smaller graphs with the nodes as `ObjectView`s.   Since the graph relates the objects in myriads ways I assume that the storage solution I choose for the objects, i.e. how they are serialized to a structure out of memory, like JSON, can be purely pragmatic.   The objects don't need to be stored in some sort of hierarchy.   Would there be some benefit in storing them in CollectionViews or something like that?  It would be nice if they were stored in a way that they could be deserialized trivially and safely back into a graph.  Of course the graph itself is easy to serialize

**Comment by zandaqo** [comment]
The view structures like ObjectView are interfaces for underlying ArrayBuffers. When instantiated separately without providing an existing ArrayBuffer, e.g. `ObjectView.from({})` they will create a new ArrayBuffer for each view. Creating an ArrayBuffer is a more involved and slower process than a normal object, so it's a good idea to have as few ArrayBuffers as possible. 

In case of multiple ObjectViews, I'd consider storing them in an ArrayView if they are of the same type, or a CollectionView of multiple ArrayViews if there are multiple types. This will result in a single ArrayBuffer for all stored ObjectViews. The major downside is that the size of the buffer (hence, the maximum number of ObjectViews in it) will be fixed upon its creation. To increase it, you'll have to create a new ArrayBuffer and copy the data since ArrayBuffers are not re-sizable. In other words, you are taking over memory management.

The question of using binary structures is the question of how dynamic is the underlying data. In this case, if the shape and amount of nodes in the graph may vary greatly, going binary would mean either pre-allocating too much memory or writing complicated algorithms for memory management. However, if the shapes are similar (ideally the same) and the amount is predictable, going binary and storing it all in a singe ArrayBuffer would minimize memory usage, and allow exchanging this data with servers, workers, and WebAssembly without serialization penalties. The C guy in me would also mention memory locality benefits, but I cannot vouch for JS engines to consistently utilize it.

**Comment by mrjjwright** [comment]
Ok, one thing I glean from this is that the it's actually better for the objects to have a root ArrayBuffer, and hence a root ObjectView which dictates their binary layout so that a new ArrayBuffer does not need to be allocated for each object.  A naive approach of creating lots of different kind of objects via `.from({})` and storing them all separately would be expensive.  If such a root arrayBuffer, or at least a few a few root binary layouts, can't be described and maintained easily, it's probably time to pause and consider what I am doing.

**Comment by mrjjwright** [comment]
Ok, one thing I glean from this is that the it's actually better for the objects to have a root ArrayBuffer, and hence a root ObjectView which dictates their binary layout so that a new ArrayBuffer does not need to be allocated for each object.  A naive approach of creating lots of different kind of objects via `.from({})` and storing them all separately would be expensive.  If such a root arrayBuffer, or at least a few a few root binary layouts, can't be described and maintained easily, it's probably time to pause and consider what I am doing.

**Comment by mrjjwright** [comment]
Also, the actual core of my app probably does have a consistent binary layout, since most of it involves JS AST nodes arranged in a graph as leaves under some other regular objects.   I am building an editor that generates JS and I like the predictable data structures I can exchange with the server (a uWebSockets.js instance) and really love this library.  So just more to think about, thank you for this wonderful lib.

**Comment by mrjjwright** [comment]
Working strategy after thinking about it this morning.   Encode edges in my graph using your `Graph` classes, to save on memory drastically.   Start with regular JS objects for the nodes but look for common structures that could share a binary layout.
