### ISSUE TITLE
Iterators / cursors

### ISSUE THREAD

**Issue by NateTheGreatt** [zandaqo/structurae#4]
Hello!

First of all, thanks for your hard work on this library! @SupremeTechnopriest and I are really loving it so far :).

I am curious if you have plans to implement, or have any ideas on a custom implementation, of iterators/cursors over your ArrayViews? I want to run small, mostly pure functions over the binary data and mutate it as I go.

**Comment by zandaqo** [comment]
Hi!

Yes, it's not described in documentation, but ArrayView does have [iterator](https://github.com/zandaqo/structurae/blob/351f65c0b66b6da09cad780e5c819cd6a36d68de/lib/array-view.js#L68). It iterates over views and you can use it in all the usual ways with for..of, destructuring, etc. I guess it's also not shown in IDEs because it's missing in the TypeScript declaration file, I'll have to fix that.

Or do you mean some other kind of iteration?

**Comment by NateTheGreatt** [comment]
Ahh okay nice. Thanks
