### ISSUE TITLE
npm test - fails, tests not passing ( TextEncoder undefined )

### ISSUE THREAD

**Issue by martindcernadas** [zandaqo/structurae#7]
Hi @zandaqo . After cloning and running the tests, they fail due to the undefined TextEncoder.
Copy that :

 FAIL  test/string-array-view.spec.js
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      362 |  * @type TextEncoder
      363 |  */
    > 364 | StringView.encoder = new TextEncoder();
          |                          ^
      365 |
      366 | /**
      367 |  * @type TextDecoder

      at Object.TextEncoder (lib/string-view.js:364:26)
      at Object.require (lib/record-array.js:17:20)

Test Suites: 6 failed, 16 passed, 22 total
Tests:       280 passed, 280 total
Snapshots:   0 total
Time:        23.737s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by martindcernadas** [comment]
It is just a dependency problem : I fixed it including:

require('fast-text-encoding');

in the file 'string-view.js' , and also installing from npm, 'npm i fast-text-encoding' .

**Comment by martindcernadas** [comment]
I would submit a fix/branch but have no write permission, sorry.

**Comment by zandaqo** [comment]
The problem is with older versions of Node or Jest that do not support [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) used by StringView. According to [this](https://nodejs.org/api/util.html#util_class_util_textencoder) Node.js supports it since version 11.0.0 I guess I should specify it in package.json as the supported engine instead of 10.4. Thank you for reporting this.

**Comment by dezren39** [comment]
> It is just a dependency problem : I fixed it including:
> 
> require('fast-text-encoding');
> 
> ## in the file 'string-view.js' , and also installing from npm, 'npm i fast-text-encoding' .
> Test Suites: 22 passed, 22 total
> Tests: 358 passed, 358 total
> Snapshots: 0 total
> Time: 13.991s
> Ran all test suites.

Thank you!!!
